/* SubTrack preset catalog — ~48 popular services.
   No trademarked logos: colored tile + category icon (see SPEC §3.2). */
(function(){
  const ST = window.ST = window.ST || {};
  // [id, name, category, brandColor, defaultMonthlyUSD, cancelUrl]
  const R = [
    ["netflix","Netflix","entertainment","#E50914",15.49,"https://www.netflix.com/cancelplan"],
    ["spotify","Spotify","music","#1DB954",11.99,"https://www.spotify.com/account/subscription/"],
    ["youtube","YouTube Premium","entertainment","#FF0000",13.99,"https://www.youtube.com/paid_memberships"],
    ["chatgpt","ChatGPT Plus","ai","#10A37F",20,"https://chat.openai.com/#settings"],
    ["claude","Claude Pro","ai","#D97757",20,"https://claude.ai/settings/billing"],
    ["icloud","iCloud+","cloud","#0A84FF",2.99,"https://support.apple.com/HT202039"],
    ["disney","Disney+","entertainment","#113CCF",13.99,"https://www.disneyplus.com/account"],
    ["max","Max","entertainment","#002BE7",16.99,"https://www.max.com/account"],
    ["appletv","Apple TV+","entertainment","#2C2C30",9.99,"https://support.apple.com/HT202039"],
    ["applemusic","Apple Music","music","#FA243C",10.99,"https://support.apple.com/HT202039"],
    ["appleone","Apple One","cloud","#3A3A3F",19.95,"https://support.apple.com/HT202039"],
    ["prime","Amazon Prime","entertainment","#00A8E1",14.99,"https://www.amazon.com/mc"],
    ["hulu","Hulu","entertainment","#1CE783",9.99,"https://secure.hulu.com/account"],
    ["crunchyroll","Crunchyroll","entertainment","#F47521",7.99,"https://www.crunchyroll.com/account"],
    ["twitch","Twitch Sub","entertainment","#9146FF",5.99,"https://www.twitch.tv/subscriptions"],
    ["gemini","Google AI Pro","ai","#4285F4",19.99,"https://one.google.com/plans"],
    ["copilot","GitHub Copilot","ai","#24292F",10,"https://github.com/settings/billing"],
    ["midjourney","Midjourney","ai","#7A78FF",10,"https://www.midjourney.com/account"],
    ["googleone","Google One","cloud","#34A853",1.99,"https://one.google.com/plans"],
    ["dropbox","Dropbox","cloud","#0061FF",11.99,"https://www.dropbox.com/account/plan"],
    ["ms365","Microsoft 365","productivity","#D83B01",9.99,"https://account.microsoft.com/services"],
    ["notion","Notion","productivity","#37352F",10,"https://www.notion.so/my-account"],
    ["figma","Figma","productivity","#F24E1E",15,"https://www.figma.com/settings"],
    ["adobe","Adobe CC","productivity","#DA1F26",59.99,"https://account.adobe.com/plans"],
    ["canva","Canva Pro","productivity","#00C4CC",12.99,"https://www.canva.com/settings/billing"],
    ["linkedin","LinkedIn Premium","productivity","#0A66C2",29.99,"https://www.linkedin.com/premium/manage"],
    ["psplus","PlayStation Plus","gaming","#0070D1",9.99,"https://www.playstation.com/support/subscriptions/"],
    ["gamepass","Xbox Game Pass","gaming","#107C10",10.99,"https://account.microsoft.com/services"],
    ["nintendo","Nintendo Online","gaming","#E60012",3.99,"https://accounts.nintendo.com/"],
    ["duolingo","Duolingo Super","education","#58CC02",6.99,"https://www.duolingo.com/settings/super"],
    ["headspace","Headspace","health","#F47D31",12.99,"https://www.headspace.com/settings"],
    ["calm","Calm","health","#4A90D9",14.99,"https://www.calm.com/account"],
    ["strava","Strava","health","#FC4C02",11.99,"https://www.strava.com/account"],
    ["fitbit","Fitbit Premium","health","#00B0B9",9.99,"https://www.fitbit.com/settings"],
    ["tinder","Tinder Gold","other","#FE3C72",24.99,"https://tinder.com/app/settings"],
    ["audible","Audible","education","#F8991C",14.95,"https://www.audible.com/account"],
    ["kindle","Kindle Unlimited","education","#FF9900",11.99,"https://www.amazon.com/kindleunlimited"],
    ["medium","Medium","education","#3A3A3F",5,"https://medium.com/me/settings"],
    ["patreon","Patreon","other","#FF424D",5,"https://www.patreon.com/settings/memberships"],
    ["nordvpn","NordVPN","cloud","#4687FF",12.99,"https://my.nordaccount.com/"],
    ["expressvpn","ExpressVPN","cloud","#DA3940",12.95,"https://www.expressvpn.com/subscriptions"],
    ["1password","1Password","cloud","#0094F5",2.99,"https://my.1password.com/billing"],
    ["telegram","Telegram Premium","other","#229ED9",4.99,"https://t.me/settings"],
    ["discord","Discord Nitro","other","#5865F2",9.99,"https://discord.com/settings/subscriptions"],
    ["xpremium","X Premium","other","#2C2C30",8,"https://twitter.com/settings/subscriptions"],
    ["deezer","Deezer","music","#A238FF",11.99,"https://www.deezer.com/account"],
    ["tidal","TIDAL","music","#121214",10.99,"https://tidal.com/account"],
    ["soundcloud","SoundCloud Go","music","#FF5500",4.99,"https://soundcloud.com/settings/subscription"],

    // ── streaming / entertainment ──
    ["peacock","Peacock","entertainment","#FA6432",7.99,""],
    ["paramount","Paramount+","entertainment","#0064FF",11.99,""],
    ["espn","ESPN+","entertainment","#CC0000",11.99,""],
    ["discovery","Discovery+","entertainment","#2175FF",8.99,""],
    ["starz","Starz","entertainment","#00A0DC",9.99,""],
    ["showtime","Showtime","entertainment","#E4002B",10.99,""],
    ["britbox","BritBox","entertainment","#16326A",8.99,""],
    ["mubi","MUBI","entertainment","#4C31C9",14.99,""],
    ["shudder","Shudder","entertainment","#E20000",6.99,""],
    ["dazn","DAZN","entertainment","#F8F800",19.99,""],
    ["fubo","FuboTV","entertainment","#EC0E43",79.99,""],
    ["sling","Sling TV","entertainment","#00A9E0",40,""],
    ["plex","Plex Pass","entertainment","#E5A00D",6.99,""],
    ["vimeo","Vimeo","entertainment","#1AB7EA",12,""],
    ["nebula","Nebula","entertainment","#3B4ECC",5,""],
    ["hotstar","Disney+ Hotstar","entertainment","#0F1B41",4.99,""],
    ["zee5","ZEE5","entertainment","#8230C6",2.99,""],
    ["sonyliv","SonyLIV","entertainment","#1A1A2E",2.99,""],
    ["jiocinema","JioCinema","entertainment","#C4181E",1.2,""],
    ["globoplay","Globoplay","entertainment","#F5001E",6,""],
    ["viki","Rakuten Viki","entertainment","#1EBEA5",4.99,""],
    ["iqiyi","iQIYI","entertainment","#00BE06",6.99,""],
    ["viu","Viu","entertainment","#FBC700",5,""],
    ["curiositystream","CuriosityStream","entertainment","#2CA6E0",4.99,""],
    ["funimation","Funimation","entertainment","#5B0BB5",5.99,""],
    ["hayu","hayu","entertainment","#FF2D6F",5.99,""],
    ["kinopoisk","Kinopoisk","entertainment","#FF5500",3,""],
    ["ivi","ivi","entertainment","#FF6600",3,""],

    // ── music / audio ──
    ["amazonmusic","Amazon Music","music","#00A8E1",10.99,""],
    ["ytmusic","YouTube Music","music","#FF0000",10.99,""],
    ["pandora","Pandora","music","#3668FF",4.99,""],
    ["siriusxm","SiriusXM","music","#0000EB",9.99,""],
    ["qobuz","Qobuz","music","#000000",12.99,""],
    ["napster","Napster","music","#3E3E3E",10.99,""],
    ["anghami","Anghami","music","#FF5B00",4.99,""],
    ["yandexplus","Yandex Plus","music","#FF3333",3,""],
    ["boomplay","Boomplay","music","#F73E01",1.99,""],
    ["pocketcasts","Pocket Casts","music","#F43E37",3.99,""],
    ["audible2","Audible Plus","education","#F8991C",7.95,""],

    // ── AI tools ──
    ["perplexity","Perplexity Pro","ai","#20808D",20,""],
    ["grammarly","Grammarly","ai","#15C39A",12,""],
    ["deepl","DeepL Pro","ai","#0F2B46",8.74,""],
    ["jasper","Jasper","ai","#FF7A59",39,""],
    ["runway","Runway","ai","#000000",15,""],
    ["elevenlabs","ElevenLabs","ai","#000000",5,""],
    ["suno","Suno","ai","#000000",10,""],
    ["gamma","Gamma","ai","#8A3FFC",10,""],
    ["character","Character.AI","ai","#0A0A23",9.99,""],
    ["leonardo","Leonardo.ai","ai","#8B5CF6",12,""],
    ["poe","Poe","ai","#5D3FD3",19.99,""],
    ["heygen","HeyGen","ai","#7C3AED",29,""],
    ["descript","Descript","ai","#2D2AF7",24,""],
    ["otter","Otter.ai","ai","#00A0DC",16.99,""],
    ["mistral","Le Chat Pro","ai","#FA5211",14.99,""],
    ["cursor","Cursor","ai","#000000",20,""],
    ["notionai","Notion AI","ai","#37352F",10,""],

    // ── productivity / work ──
    ["slack","Slack","productivity","#4A154B",8.75,""],
    ["zoom","Zoom","productivity","#0B5CFF",13.99,""],
    ["trello","Trello","productivity","#0079BF",5,""],
    ["asana","Asana","productivity","#F06A6A",10.99,""],
    ["todoist","Todoist","productivity","#E44332",4,""],
    ["evernote","Evernote","productivity","#00A82D",10.83,""],
    ["clickup","ClickUp","productivity","#7B68EE",7,""],
    ["monday","monday.com","productivity","#FF3D57",9,""],
    ["airtable","Airtable","productivity","#18BFFF",20,""],
    ["miro","Miro","productivity","#FFD02F",8,""],
    ["loom","Loom","productivity","#625DF5",12.50,""],
    ["calendly","Calendly","productivity","#006BFF",10,""],
    ["zapier","Zapier","productivity","#FF4A00",19.99,""],
    ["superhuman","Superhuman","productivity","#000000",30,""],
    ["obsidian","Obsidian Sync","productivity","#7C3AED",4,""],
    ["things","Things","productivity","#3B82F6",0,""],
    ["fantastical","Fantastical","productivity","#F53232",4.75,""],
    ["grammarly2","Reclaim","productivity","#4C6EF5",8,""],
    ["basecamp","Basecamp","productivity","#1D2D35",15,""],
    ["linear","Linear","productivity","#5E6AD2",8,""],

    // ── cloud / storage / dev / web ──
    ["onedrive","OneDrive","cloud","#0364B8",1.99,""],
    ["box","Box","cloud","#0061D5",10,""],
    ["mega","MEGA","cloud","#D9272E",5.83,""],
    ["pcloud","pCloud","cloud","#00BFEB",4.99,""],
    ["backblaze","Backblaze","cloud","#E21E29",9,""],
    ["protonmail","Proton","cloud","#6D4AFF",4.99,""],
    ["protondrive","Proton Drive","cloud","#6D4AFF",4.99,""],
    ["github","GitHub Pro","productivity","#24292F",4,""],
    ["gitlab","GitLab","productivity","#FC6D26",29,""],
    ["vercel","Vercel","cloud","#000000",20,""],
    ["netlify","Netlify","cloud","#00C7B7",19,""],
    ["digitalocean","DigitalOcean","cloud","#0080FF",6,""],
    ["cloudflare","Cloudflare","cloud","#F38020",5,""],
    ["namecheap","Namecheap","cloud","#DE3910",5,""],
    ["squarespace","Squarespace","cloud","#000000",16,""],
    ["wix","Wix","cloud","#0C6EFC",16,""],
    ["wordpress","WordPress.com","cloud","#21759B",8,""],
    ["webflow","Webflow","cloud","#4353FF",14,""],
    ["fastmail","Fastmail","cloud","#0067B9",5,""],
    ["zoho","Zoho","productivity","#E42527",1,""],

    // ── gaming ──
    ["eaplay","EA Play","gaming","#FF4747",4.99,""],
    ["ubisoft","Ubisoft+","gaming","#000000",17.99,""],
    ["geforcenow","GeForce Now","gaming","#76B900",9.99,""],
    ["applearcade","Apple Arcade","gaming","#F84B5D",6.99,""],
    ["playpass","Google Play Pass","gaming","#00A0DC",4.99,""],
    ["roblox","Roblox Premium","gaming","#E2231A",4.99,""],
    ["wow","WoW","gaming","#00AEFF",14.99,""],
    ["ffxiv","FFXIV","gaming","#1E3A8A",12.99,""],
    ["humble","Humble Choice","gaming","#CB272C",11.99,""],
    ["minecraft","Minecraft Realms","gaming","#5A9C43",7.99,""],

    // ── health / fitness / mind ──
    ["peloton","Peloton App","health","#181818",12.99,""],
    ["fitnessplus","Apple Fitness+","health","#A4F82E",9.99,""],
    ["myfitnesspal","MyFitnessPal","health","#0066EE",19.99,""],
    ["whoop","WHOOP","health","#000000",30,""],
    ["oura","Oura","health","#0A0A0A",5.99,""],
    ["noom","Noom","health","#FF6B4A",70,""],
    ["fitbod","Fitbod","health","#2F6BFF",12.99,""],
    ["freeletics","Freeletics","health","#F5003C",11.99,""],
    ["nikeplus","Nike Training Club","health","#111111",0,""],
    ["centr","Centr","health","#00B3A6",29.99,""],
    ["flo","Flo Premium","health","#FF6B9D",9.99,""],
    ["clue","Clue Plus","health","#E5006D",1.99,""],
    ["betterhelp","BetterHelp","health","#00838F",65,""],
    ["talkspace","Talkspace","health","#00C1A2",69,""],
    ["tenpercent","Ten Percent Happier","health","#F5A623",9.99,""],
    ["insighttimer","Insight Timer","health","#E94F37",5.99,""],
    ["yazio","YAZIO","health","#00C08B",8.33,""],

    // ── education / reading / news ──
    ["coursera","Coursera Plus","education","#0056D2",59,""],
    ["udemy","Udemy","education","#A435F0",16.58,""],
    ["skillshare","Skillshare","education","#00FF84",13.99,""],
    ["masterclass","MasterClass","education","#E50914",10,""],
    ["babbel","Babbel","education","#FF9B00",13.95,""],
    ["busuu","Busuu","education","#0B84FE",9.99,""],
    ["rosetta","Rosetta Stone","education","#0098DB",11.99,""],
    ["blinkist","Blinkist","education","#00B871",15.99,""],
    ["everand","Everand (Scribd)","education","#1E7B85",11.99,""],
    ["brilliant","Brilliant","education","#FCBF00",13.49,""],
    ["codecademy","Codecademy","education","#1F4056",17.99,""],
    ["datacamp","DataCamp","education","#03EF62",12.42,""],
    ["pluralsight","Pluralsight","education","#F15B2A",29,""],
    ["quizlet","Quizlet Plus","education","#4257B2",7.99,""],
    ["nyt","NY Times","education","#000000",4.25,""],
    ["wsj","WSJ","education","#0274B6",9.99,""],
    ["wapo","Washington Post","education","#000000",4,""],
    ["economist","The Economist","education","#E3120B",16.99,""],
    ["bloomberg","Bloomberg","education","#000000",34.99,""],
    ["ft","Financial Times","education","#FFF1E5",39,""],
    ["athletic","The Athletic","education","#000000",7.99,""],
    ["substack","Substack","education","#FF6719",5,""],

    // ── VPN / security ──
    ["surfshark","Surfshark","cloud","#178A7E",12.95,""],
    ["protonvpn","ProtonVPN","cloud","#6D4AFF",9.99,""],
    ["mullvad","Mullvad","cloud","#294D73",5,""],
    ["cyberghost","CyberGhost","cloud","#FFCC00",12.99,""],
    ["pia","Private Internet Access","cloud","#4CB749",11.95,""],
    ["windscribe","Windscribe","cloud","#4990E2",9,""],
    ["bitwarden","Bitwarden","cloud","#175DDC",10,""],
    ["dashlane","Dashlane","cloud","#0E353D",4.99,""],
    ["lastpass","LastPass","cloud","#D32D27",3,""],
    ["malwarebytes","Malwarebytes","cloud","#1A73E8",3.33,""],
    ["mcafee","McAfee","cloud","#C01818",8.33,""],
    ["norton","Norton 360","cloud","#FFE01B",9.99,""],
    ["bitdefender","Bitdefender","cloud","#ED1C24",5.99,""],

    // ── dating ──
    ["bumble","Bumble","other","#FFC629",24.99,""],
    ["hinge","Hinge","other","#8B0000",29.99,""],
    ["grindr","Grindr","other","#FFDA00",19.99,""],
    ["okcupid","OkCupid","other","#0500BE",19.99,""],
    ["match","Match","other","#E92434",23.99,""],
    ["badoo","Badoo","other","#7B3AED",12.99,""],
    ["pof","Plenty of Fish","other","#00A0DC",19.99,""],
    ["cmb","Coffee Meets Bagel","other","#8B5C2A",34.99,""],

    // ── food / delivery / shopping ──
    ["uberone","Uber One","other","#000000",9.99,""],
    ["dashpass","DashPass","other","#EB1700",9.99,""],
    ["instacart","Instacart+","other","#43B02A",9.99,""],
    ["walmart","Walmart+","other","#0071DC",12.95,""],
    ["hellofresh","HelloFresh","other","#91C11E",0,""],
    ["costco","Costco","other","#005DAA",5,""],
    ["deliveroo","Deliveroo Plus","other","#00CCBC",3.49,""],
    ["grubhub","Grubhub+","other","#F63440",9.99,""],
    ["samsclub","Sam's Club","other","#0067A0",4.17,""],

    // ── creative / design / stock ──
    ["affinity","Affinity","productivity","#1B2A47",8.25,""],
    ["framer","Framer","productivity","#0055FF",5,""],
    ["envato","Envato Elements","productivity","#82B541",16.50,""],
    ["shutterstock","Shutterstock","productivity","#E51937",29,""],
    ["adobestock","Adobe Stock","productivity","#DA1F26",29.99,""],
    ["epidemic","Epidemic Sound","music","#1D1D1D",9,""],
    ["artlist","Artlist","music","#00E0B8",9.99,""],
    ["capcut","CapCut Pro","productivity","#000000",7.99,""],

    // ── finance / misc ──
    ["ynab","YNAB","finance","#0DA5E9",14.99,""],
    ["quicken","Quicken","finance","#7B1FA2",4.17,""],
    ["robinhood","Robinhood Gold","finance","#00C805",5,""],
    ["empower","Empower","finance","#1C7C54",8,""],
    ["creditkarma","Credit Karma","finance","#00B98D",0,""],
    ["acorns","Acorns","finance","#6F2DBD",3,""],
    ["revolut","Revolut Premium","finance","#0666EB",9.99,""],
    ["monzo","Monzo Plus","finance","#FF3464",5,""],

    // ── other popular ──
    ["strava2","Komoot","health","#6AA127",4.99,""],
    ["duolingomax","Duolingo Max","education","#58CC02",13.99,""],
    ["applenews","Apple News+","education","#FA2D48",12.99,""],
    ["onlyfans","OnlyFans","other","#00AFF0",9.99,""],
    ["twitchturbo","Twitch Turbo","entertainment","#9146FF",11.99,""],
    ["patreonmember","Ko-fi Gold","other","#FF5E5B",6,""],
    ["setapp","Setapp","productivity","#E6357A",9.99,""],
    ["cleanmymac","CleanMyMac","productivity","#7B61FF",4.95,""],
    ["1blocker","1Blocker","productivity","#3B82F6",2.99,""],
    ["ivacy","Ivacy VPN","cloud","#3F51B5",9.95,""],
    ["skype","Skype Credit","other","#00AFF0",5,""],
    ["wetransfer","WeTransfer Pro","cloud","#409FFF",12,""],
    ["temu","Temu","other","#FB7701",0,""],
    ["chegg","Chegg","education","#EA6100",15.95,""],
    ["grammarlybiz","Speechify","ai","#4B2AF7",11.58,""],
  ];
  ST.PRESETS = R.map(r=>({id:r[0], name:r[1], category:r[2], color:r[3], priceUSD:r[4], cancelUrl:r[5]}));
  ST.preset = id => ST.PRESETS.find(p=>p.id===id);

  /* short step-by-step cancel instructions (service UIs are in English) */
  ST.GUIDES = {
    netflix:"Account → Membership → Cancel membership",
    spotify:"Account → Your plan → Change plan → Cancel Premium",
    youtube:"Paid memberships → Manage → Deactivate",
    chatgpt:"Settings → Subscription → Manage → Cancel plan",
    claude:"Settings → Billing → Cancel subscription",
    icloud:"iPhone Settings → your name → Subscriptions → iCloud+ → Cancel",
    appletv:"iPhone Settings → your name → Subscriptions → Apple TV+ → Cancel",
    applemusic:"iPhone Settings → your name → Subscriptions → Apple Music → Cancel",
    appleone:"iPhone Settings → your name → Subscriptions → Apple One → Cancel",
    disney:"Account → Subscription → Cancel subscription",
    max:"Profile → Subscription → Manage → Cancel",
    prime:"Account → Prime membership → Manage → End membership",
    hulu:"Account → Your subscription → Cancel",
    gamepass:"Microsoft account → Services & subscriptions → Manage → Turn off recurring billing",
    ms365:"Microsoft account → Services & subscriptions → Manage → Cancel",
    psplus:"Console: Settings → Users and Accounts → Payment and Subscriptions → Subscriptions",
    nintendo:"Nintendo eShop → Account → Subscriptions → Turn off auto-renewal",
    duolingo:"Profile → Settings → Super Duolingo → Cancel subscription",
    googleone:"one.google.com → Settings → Cancel membership",
    gemini:"one.google.com → Settings → Cancel membership",
    dropbox:"Settings → Plan → Cancel plan",
    notion:"Settings & members → Plans → Downgrade",
    figma:"Settings → Billing → Change plan",
    adobe:"Account → Plans → Manage plan → Cancel plan (watch for early-termination fee)",
    canva:"Settings → Billing & plans → Cancel subscription",
    linkedin:"Me → Premium features → Manage → Cancel subscription",
    telegram:"Settings → Telegram Premium → Manage → Cancel",
    discord:"User Settings → Subscriptions → Cancel",
    nordvpn:"Nord Account → Billing → Subscriptions → Cancel auto-renewal",
    audible:"Account details → Membership → Cancel membership",
    kindle:"Amazon → Memberships & subscriptions → Manage → Cancel",
    tinder:"Profile → Settings → Manage payment account → Cancel",
    headspace:"Profile → Settings → Manage subscription → Cancel",
    calm:"calm.com → Profile → Manage Subscription → Cancel",
    strava:"Settings → My account → Subscription → Cancel",
  };
  // shown on onboarding + top of Add screen
  ST.POPULAR = ["netflix","spotify","youtube","chatgpt","icloud","prime","disney","applemusic","gamepass","duolingo","claude","googleone"];
})();
